name: Run autotests


on:
    workflow_dispatch:
      inputs:
        deployment_target:
          description: select tests to run
          required: true
          type: choice
          default: all
          options:
            - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: tests
    steps: 
      - name: Copy source code
        uses: action/checkout@v4
      - name: Set up Python env
        uses: action/setup-python@v5
        with: 
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v
      
